# -*- coding: utf-8 -*-
"""mini_proj2_rub.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/matthigger/cs2810/blob/main/mini_proj2_rub.ipynb

# Mini Project 2 (22 points total)

Complete the Jupyter Notebook below with your group of two to four students.  You need only submit one Jupyter Notebook to [gradescope](https://www.gradescope.com/courses/347537/assignments/2012798/) for your whole group (be sure to add all group members).  

While you may submit your groups work to gradescope anytime until **April 26 @ 11:59PM** my expectation is that most of the work can be completed in class today.

________________

In this Mini Project, you'll write two homework problems of your choosing.  

# Can future courses re-use these problems? (please?)
We'd love to be able to use these problems in a future semester.  If you'd allow us, please save this jupyter notebook and, in addition to submitting on gradescope, upload [here](https://www.dropbox.com/request/wdM7nfvpxGUvKXdmUqgu).  (This is entirely optional)

We're happy to cite your team, our source for these problems.  If you'd like to be acknowledged, please include your email addresses in the cell below.  You're welcome to leave the cell below blank if you prefer to not have your emails associated with your problem.

Know that we'll very likely edit a problem before sharing with future students.
"""

panjabi.d@northeastern.edu,   hoang.andr@northeastern.edu

"""# Data Sources

- [google dataset search](https://datasetsearch.research.google.com/)
- [kaggle](https://kaggle.com/)
- [Global Health Observatory](https://apps.who.int/gho/data/node.home)
- [UCI Machine Learning Repo](https://archive.ics.uci.edu/ml/index.php)
- [data.gov](https://www.data.gov/)
- [FiveThirtyEight](https://data.fivethirtyeight.com/)

# Part 1: Hypothesis Test / Cov&Corr / theory problem

Choose any application of interest and write a multi-part homework problem which practices it.  The best problems:
- have clean connections between the "application story" and the mathematics
- are fun and interesting to think about

Below we list some popular topics for homework problems:

- **hypothesis tests:**
    - t-test
        - is it 1 or 2 sided?
    - chi square test
        - what is the target distribution you're comparing to?
            - some known discrete distribution
            - binomial
            - poisson
            - (whatever the target distribution you're comparing to, be sure its reasonable)
- hypothesis test considerations:
    - can you source real data for this data or must you make up numbers?
    - be sure the problem can be done with pencil / paper
        - limit sample sizes to what can be computed by hand

- **covariance / correlation**
    - identify some interesting question which can be answered from observing correlation / covariance
    - you must source real data for this
    - once you have a csv of real data,you can get the correlation / covariance matrix via:
    
```python
import pandas as pd

df = pd.read_csv('your_csv_file_here.csv')

# covariance
df.cov()

# correlation matrix
df.corr()
```

- **theory / application problem**
    - there's a few interesting ideas you could ask a question about in some application
        - law of large numbers
        - central limit theorem
        
Choose one of the three bolded problem topics above and write a homework problem below:
- give a clean description which is easily understood by all students
- scaffold your questions from easy to hard
    - if a question, as posed, is too difficult you might consider leading student by breaking it into two
- write a solution for each part, which in addition to being correct, is clear enough to allow students to learn why its correct while reading it

### Part 1 (rubric):
- 3 problem is original / interesting
- 3 problem is appropriately expansive / difficult enough for CS2810 students
    - you can pose something as "extra credit" if its a stretch, but be sure its accesible extra credit
- 3 problem is written clearly and succinctly
- 3 solution is correct
- 3 solution is clear

**Problem 1: Chi-Squared** 

The number of red lights that were ran in the city of Boston through out the day is represented by the table below.


| 8-9am | 9-10am | 10-11am | 11-12pm | 12-1pm | 1-2pm | 2-3pm | 3-4pm |
|-------|--------|---------|---------|--------|-------|-------|-------|
| 11    | 8      | 10      | 6       | 7      | 8     | 6     | 11    |

i) What is the Poisson distribution average rate of red lights ran per hour?

ii) Create a chi-squared table of observed red lights ran from 9 and below, 10-15, 15-20, 20-25, 25-30, and 30-35.

iii) Calculate the probabilities of each outcome above using the Poisson Distribution from part i.

iv) Create a chi-squared goodness of fit test with the expected Poisson Distribution and determine if the Poisson model is either rejected or accepted.\

Solution:

i) λ = 7 : the average rate of these values 

ii) 

| x           | 6 | 7 | 8 | 9 | 10 | 1 |
|-------------|---|---|---|---|----|---|
| x(observed) | 2 | 1 | 2 | 0 | 1  | 2 |

iii) 
p(6) = 0.149 ,
p(7) = 0.149 ,
p(8) = 0.130 ,
p(9) = 0.101 ,
p(10) = 0.0710 ,
p(11) = 0.0452 ,

iv)

x^2 = 23.1

p-val = 0.00163

We would reject the Poisson model because it is less than 0.05.

# Part 2: Build a Bayes Network

In this part, build a homework problem on a Bayes Net on a topic of your choosing.

- Bayes network on four nodes
    - too many nodes and the joint distribution table has too many rows ...
- ask the student 3 or 4 questions which build towards some intuition
    - demonstrate / explain a conditional independence relationship
    - demonstrate some intuition encapsulated in the network:
        - e.g. in HW9 problem 4: "defending a basketball shot decreases the expected points earned"


Your submission should include 4 items:
- the text of the problem
- the solution to each part
- the image of the bayes net (appendix 1)
- the joint distribution table (appendix 2)

# Part 2 (rubric):
- 3 problem is original / interesting
- 3 problem is appropriately expansive / difficult enough for CS2810 students
    - you can pose something as "extra credit" if its a stretch, but be sure its accesible extra credit
- 3 problem is written clearly and succinctly
- 3 solution is correct
- 3 solution is clear
- 3 image of bayes net neat, fully specified and included in jupyter
- 3 markdown table of joint distribution included in jupyter and correct

### Appendix 1: Uploading an image into a jupyter notebook
To create the image of your bayes net 
- be sure to include all probabilities needed to fully specify it
- generate an image:
    - draw one and take a picture with your phone
        - cam scanner please
    - build it on the computer
    - draw on a tablet
- upload into the notebook by:
    - uploading your image to [https://imgbb.com/](https://imgbb.com/)
    - double clicking this jupyter cell
    - replacing the hyperlink below with a hyperlink to your image
        - (should have similar format as the example given)
        - try right clicking "copy image address" or similar

<img src="https://i.ibb.co/XVXJmH3/miniproject.png" width=500px>

**Problem 2: Bayes Network**

T (On Time): whether the student is on time (t1) or late (t0)

B (Late Bus): whether the bus is on time(B1) or late (b0)

S (Snooze): if the student snoozed (s1) or woke up (s0)

A (Alarm): whether alarm went off (a1) or did not go off (a0)

(i) Compute the percentage of days that a person does not does not snooze the alarm according to this model. Show your work using the algebraic method.

(ii) Use the spreadsheet method to find (T, B| S_1). That is give the probability of every pair of outcomes that the person on time with the Bus on given that he snoozed.

(iii) Use the algebraic method to find (T, B| S_0). Give the probability of every pair of outcomes that the person is on time with the Bus given that he did not snooze.

Solution:

| T = On Time | B= Late Bus | S = Snooze | A= Alarm | P(A)  | P(S A) | P(S A B) | P(T S A B ) |
|-------------|-------------|------------|----------|-------|--------|----------|-------------|
| t0          | b0          | s0         | a0       |   0.2 |   0.04 |    0.028 |      0.0056 |
| t0          | b0          | s0         | a1       |   0.8 |   0.64 |    0.448 |      0.0896 |
| t0          | b0          | s1         | a0       |   0.2 |   0.16 |    0.112 |      0.0672 |
| t0          | b0          | s1         | a1       |   0.8 |   0.16 |    0.112 |      0.0672 |
| t0          | b1          | s0         | a0       |   0.2 |   0.04 |    0.012 |      0.0084 |
| t0          | b1          | s0         | a1       |   0.8 |   0.64 |    0.192 |      0.1344 |
| t0          | b1          | s1         | a0       |   0.2 |   0.16 |    0.048 |      0.0384 |
| t0          | b1          | s1         | a1       |   0.8 |   0.16 |    0.048 |      0.0384 |
| t1          | b0          | s0         | a0       |   0.2 |   0.04 |    0.028 |      0.0224 |
| t1          | b0          | s0         | a1       |   0.8 |   0.64 |    0.448 |      0.3584 |
| t1          | b0          | s1         | a0       |   0.2 |   0.16 |    0.112 |      0.0448 |
| t1          | b0          | s1         | a1       |   0.8 |   0.16 |    0.112 |      0.0448 |
| t1          | b1          | s0         | a0       |   0.2 |   0.04 |    0.012 |      0.0036 |
| t1          | b1          | s0         | a1       |   0.8 |   0.64 |    0.192 |      0.0576 |
| t1          | b1          | s1         | a0       |   0.2 |   0.16 |    0.048 |      0.0096 |
| t1          | b1          | s1         | a1       |   0.8 |   0.16 |    0.048 |      0.0096 |
 

(i): 

<img src="https://i.ibb.co/fd7tVnk/Miniproject-P2.png" width=400px>

(ii): 0.0672 + 0.0672 + 0.0384 + 0.0384 + 0.0448 + 0.0448 + 0.0096 + 0.0096 = 0.32



(iii): 

<img src="https://i.ibb.co/M628SCh/miniprojectp2p2.png" width=500px>

### Appendix 2: Making a table in a jupyter notebook

- make table in your favorite spreadsheet application
- copy / paste into [https://www.tablesgenerator.com/markdown_tables](https://www.tablesgenerator.com/markdown_tables)
- copy / paste from markdown table generator into a markdown cell in jupyter
"""